//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by xmsol.rc
//
#define IDI_MAINICON                    1
#define IDR_ACCELERATOR                 3
#define IDR_MENU                        4
#define IDD_KEYS                        7
#define IDB_TOOLBAR                     10
#define IDC_STATIC      (-1)
#define IDC_KEYCMD                      101
#define IDC_MENUDROP                    102
#define IDC_KEY                         103
#define IDC_AUTODELAY                   103
#define IDC_BORDER_LR                   104
#define IDC_UNDODELAY                   104
#define IDC_BORDER_UD                   105
#define IDC_RIGHTCLICKDELAY             105
#define IDC_STOCKDELAY                  106
#define IDC_CURSORMOVE                  107
#define IDD_ABOUT                       108
#define OPTIONS_ANIMATION               109
#define OPTIONS_DISPLAY                 110
#define IDD_GAMELIST                    111
#define IDB_ASCDESC                     113
#define OPTIONS_SCORE                   114
#define IDD_RULES                       115
#define IDD_NUMBER                      118
#define ID_EXIT                         201
#define ID_NEWGAME                      202
#define ID_LIST                         203
#define ID_TOOLBAR                      204
#define ID_KEYS                         205
#define ID_OPTIONS                      206
#define ID_PLAYER                       207
#define ID_DELINI                       208
#define ID_UNDO                         209
#define ID_REDO                         210
#define ID_UNDO_ALL                     211
#define ID_REDO_ALL                     212
#define ID_MIRROR_LR                    213
#define ID_MIRROR_UD                    214
#define ID_HELP_CONTENT                 215
#define ID_HELP_RULES                   216
#define ID_ABOUT                        217
#define ID_INCR_SEQ                     218
#define ID_DECR_SEQ                     219
#define ID_REFRESH                      220
#define ID_SHOWTOOLBAR                  221
#define ID_NEXT_BACK                    222
#define ID_PREV_BACK                    223
#define ID_NEXT_BKGND                   224
#define ID_PREV_BKGND                   225
#define ID_GAME_NUMBER                  226
#define ID_RANDOM_GAME                  227
#define ID_STATISTIC                    228
#define ID_NEXT_CARD                    229
#define ID_PREV_CARD                    230
#define IDC_SCMD                        510
#define IDC_SKEY                        511
#define IDC_AUTOPLAY                    514
#define IDC_SHOWRULES                   515
#define IDL_BORDER                      516
#define IDL_LR                          517
#define IDL_UD                          518
#define IDL_SEQ_DIST                    519
#define IDL_VERTICAL                    520
#define IDL_HORIZ                       521
#define IDL_CARD_VIS                    522
#define IDL_CARD_HIDDEN                 523
#define IDL_TOTAL                       524
#define IDL_UNDO                        525
#define IDL_WRONG_MOVE                  526
#define IDL_REDEAL                      527
#define IDL_MOVE_FOUNDATION             528
#define IDL_UNHIDE                      529
#define IDC_ANIM_AUTOPLAY               530
#define IDC_ANIM_UNDO                   531
#define IDC_ANIM_RIGHTCLICK             532
#define IDC_ANIM_STOCK                  533
#define IDL_CORNERS                     534
#define IDL_TIME                        535
#define IDL_GAMENUMBER                  536
#define IDC_BEST_SCORES                 537
#define IDL_BONUS                       539
#define IDC_HALFTONE                    540
#define IDC_SEQDIST_X                   1006
#define IDC_SEQDIST_HX                  1007
#define IDC_LIST                        1007
#define IDC_SEQDIST_Y                   1008
#define IDC_TOTAL                       1008
#define IDC_SEQDIST_HY                  1009
#define IDC_SCORE_FOUNDATION            1009
#define IDC_SCORE_UNHIDE                1010
#define IDC_SCORE_UNDO                  1011
#define IDC_SCORE_BONUS                 1012
#define IDC_SCORE_WRONG_MOVE            1013
#define IDC_SCORE_REDEAL                1014
#define IDC_SCORE_TIME                  1015
#define IDC_RULES                       1016
#define IDC_CORNERS                     1019
#define IDC_PREVIEW                     1021
#define IDC_GAMENUMBER                  1022
#define ID_ACCEL40001                   40001
#define ID_LASTGAME                     40008
#define ID_RELOADGAME                   40012
#define ID_CARDS                        45000
#define ID_BKGND                        50000
#define ID_BACK                         55000
#define ID_CELL                         60000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        119
#define _APS_NEXT_COMMAND_VALUE         40014
#define _APS_NEXT_CONTROL_VALUE         1025
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
